GET http://localhost:3001/alumno
#######

GET http://localhost:3001/alumno/1

#######
POST http://localhost:3001/alumno
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Lopez",
    "idCarrera": 1
}

######

PUT http://localhost:3001/alumno
Content-Type: application/json

{
    "id": 2,
    "nombre": "Ana Lucia",
    "apellido": "Mendez",
    "curso": "Derecho Penal"
}

######
DELETE http://localhost:3001/alumno/1