GET http://localhost:3001/carrera
#######

POST http://localhost:3001/carrera
Content-Type: application/json

{
    "nombre": "Ingenieria de Sistemas"
}

#######

GET http://localhost:3001/carrera/2

#######

PUT http://localhost:3001/carrera
Content-Type: application/json

{
    "id": "3",
    "nombre": "Arquitectura"
}