GET http://localhost:3001/docentes
########

POST http://localhost:3001/docentes/
Content-Type: application/json

{
    "nombre": "Juan", 
    "apellido": "Gomez"
}
###

PUT http://localhost:3001/docentes/
Content-Type: application/json

{
    "id": 3, 
    "nombre": "Thalia", 
    "apellido": "Sanches"
}

###

GET http://localhost:3001/docentes/2
###

DELETE http://localhost:3001/docentes/1